blank_issues_enabled: false
contact_links:
  - name: 💬 Potrzebujesz pomocy? / Need Help?
    url: https://github.com/YOUR-REPO/discussions
    about: Użyj zakładki Discussions, jeśli chcesz zapytać lub przedyskutować temat.